client_config_backend: file
client_config:
    client_id: 948498218733-aautsntpo3o38vkeqh4e17sg2d2kdhg3.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive